### ISSUE TITLE
Gas optimization questions about calldata and memory

### ISSUE THREAD

**Issue by usgeeus** [tokamak-network/multisender_shivansh#5]
**Configuration**
- Severity: LOW

Just a question:
The functions are getting the parameter values in calldata, and calldataload all the values, and mstore them. Have you ever tried to measure the gas cost by getting the function parameters in memory from the beginning by specifying `memory` instead of `calldata` and remove all the `calldataload` and `mstore`?? Just curious.

**Comment by Shivansh070707** [comment]
calldata is cheaper than memory

**Comment by usgeeus** [comment]
I am asking because calldata is not always cheap. All the functions you developed have the extra logic of copying all the calldata into memory now. If you're going to use only memory anyway, you don't need to use the calldata from beginning and can avoid using `calldataload` and `mstore`. So using memory can lead to gas optimization.
But since you say calldata is cheaper, so I assume that's the case, thank you for checking.

**Comment by nguyenzung** [comment]
Correct me If I am wrong, if we declare memory instead of calldata for function inputs, there are still calldata and solidity will copy calldata to memory by using calldatacopy() before the function's body is executed.

**Comment by usgeeus** [comment]
Oh yeah I think you are right thanks, I'll close this issue.
